FROM julia:1.11.1

WORKDIR /app

ENV JULIA_CPU_TARGET=generic

RUN julia -e 'using Pkg;Pkg.add(Pkg.PackageSpec(;name="GDAL_jll", version="301.900"));Pkg.add(url="https://github.com/f-tommy/SeaGap.git");Pkg.add("Plots");using SeaGap'

CMD ["julia"]